name: Build Python Executables

on:
  push:
    branches: [ "executables" ] # Triggers the workflow on push to the main branch
  pull_request:
    branches: [ "executables" ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Or your desired python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed app.py # Use your own PyInstaller command here

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-${{ matrix.os }}
        path: |
          dist/*.exe
          dist/*.dmg
          dist/* # Adjust path based on the OS and output of PyInstaller
